### PR TITLE
fix: export button placement in text mode

### PR DESCRIPTION
**Pull request by jakubfronczyk**
Change button placement outside `<pre>` tag.

I spotted types problem. I used custom types from `types/github.ts` file.

### CODE REVIEW

**Comment by jakubfronczyk** [comment]
I get "Binding element 'repository' implicitly has an `any` type.
Error that occurs when TypeScript can't determine the type of a variable or parameter automatically.
To address this issue, I added explicit type annotations using our custom types.
By specifying the expected types for `repository` and `contributions` using the custom `PullRequestContributionsByRepository` type, we could enhance type-safety and catch potential type-related issues at compile time.

**Comment by Balastrong** [comment]
Thanks for the details! I'm asking because on visual studio code I already see the types there properly.
Are you using some strict extension or a different editor?

`repositories` is already typed and it's an array, I'm assuming calling `.map` on it should infer the types of each element with no effort.

What happens if you explicitly type it on line 18 instead? Would that still need the extra typings in the `.map`?
```
  const {
    repositories,
    isLoading,
  }: {
    repositories: PullRequestContributionsByRepository[];
    isLoading: boolean;
  } = useGitHubPullRequests(year, login as string);
```

**Comment by jakubfronczyk** [comment]
I'm using the VSCode and if i'm not wrong it's not specifically related to an extension, when you have the TypeScript language service enabled the editor itself will highlight these errors.

Your apporach also works and we don't need extra typing in `.map` 
I'm thinking it is even better becasue also ensures type safety across your codebase wherever these variables are used.

**Comment by Balastrong** [comment]
That's great, thank you!

Then if that's also ok for you to move that type there I'll merge the PR after your commit :)

**Comment by jakubfronczyk** [comment]
I pushed changes.

Thank you :)
It seems really fun project, I hope I could help more.

**Review by Balastrong — APPROVED** [review]
LGTM! Thanks a lot :D

**Comment by Balastrong** [comment]
@all-contributors please add @jakubfronczyk for code

**Pull request merged**
