### PR TITLE
feat: dark mode toggle

### PR DESCRIPTION
**Pull request by black-arm**

### CODE REVIEW

**Comment by Balastrong** [comment]
Thank you for the PR!

The theme changes seems to be working fine, but the light theme has quite some issues, in particular in the navbar as mentioned in #48 

@Agrimaagrawal maybe you can work with @black-arm to take care about that? I'd probably like to see the light theme fixed first, so we can safely merge this PR to show the toggle to everyone.

What do you think?

**Comment by black-arm** [comment]
Hi, I found problems with system preferences: 
```css
:root {
  --foreground-rgb: 0, 0, 0;
  --background-start-rgb: 214, 219, 220;
  --background-end-rgb: 255, 255, 255;
}

@media (prefers-color-scheme: dark) {
  :root {
    --foreground-rgb: 255, 255, 255;
    --background-start-rgb: 0, 0, 0;
    --background-end-rgb: 0, 0, 0;
  }
}

body {
  color: rgb(var(--foreground-rgb));
  background: linear-gradient(
      to bottom,
      transparent,
      rgb(var(--background-end-rgb))
    )
    rgb(var(--background-start-rgb));
}
```
With this properties if I choose light theme at the evening I have the components light but the body black. The solution is to add this properties in tailwind and to add the item system in the dropdown.

**Comment by Balastrong** [comment]
Thank you for the update, looks a lot nicer now!

Just a couple more colors that should be changed on light mode are when buttons are hovered and the background of the card.

image

If you fix these two I think everything else is great on this PR :D

**Review by Balastrong — CHANGES_REQUESTED** [review]
Thank you for the update, looks a lot nicer now!

Just a couple more colors that should be changed on light mode are when buttons are hovered and the background of the card.

image

If you fix these two I think everything else is great on this PR :D

**Comment by Balastrong** [comment]
LGTM, thank you for all the fixes! :)

**Review by Balastrong — APPROVED** [review]

**Pull request merged**
