### PR TITLE
feat: add text for no-results

### PR DESCRIPTION
**Pull request by theanantchoubey**
This PR resolves the #23 Issue.
In case of non-availability of the data in a specific year, it shows "No Contribution" as text.

### CODE REVIEW

**Comment by Balastrong** [comment]
Thanks for the PR!

We already had a nested ternary to display the three different modes, I'd rather not add an extra ternary on top of this, we should refactor things a little bit.

I would be ok with either an IIFE for the three `format`s or extracting something into separate functions/components.

(also don't forget to format your code with prettier)

**Comment by theanantchoubey** [comment]
Ok Thanks for the corrections!
I will implement it and get back then.

**Comment by theanantchoubey** [comment]
Please have a review, I have made the required changes.

**Review by Balastrong — APPROVED** [review]
LGTM, well done and thank you for your collaboration!

**Pull request merged**
